export const TrendingTools = [
  {
    id: 1,
    date: "17 Nov",
    name: "DocGPT",
  },
  {
    id: 2,
    date: "17 Nov",
    name: "DocGPT",
  },
  {
    id: 3,
    date: "17 Nov",
    name: "DocGPT",
  },
  {
    id: 4,
    date: "17 Nov",
    name: "DocGPT",
  },
  {
    id: 5,
    date: "17 Nov",
    name: "DocGPT",
  },
  {
    id: 6,
    date: "17 Nov",
    name: "DocGPT",
  },
  {
    id: 7,
    date: "17 Nov",
    name: "DocGPT",
  },
  {
    id: 8,
    date: "17 Nov",
    name: "DocGPT",
  },
  {
    id: 9,
    date: "17 Nov",
    name: "DocGPT",
  },
  {
    id: 10,
    date: "17 Nov",
    name: "DocGPT",
  },
];

export const ExploreTools = [
  {
    id: 1,
    date: "17 Nov",
    name: "deBunkD",
    rating: 2.1,
    featured: true,
    tags: ["Education", "Student"],
    image: "/debunked.png",
    description:
      "Debunkd is an AI-powered fact-checker and image detector tool that helps you verify the authenticity of information you come across online. Whether it's a tweet, a picture, or even a chat, Debunkd can double-check things.",
  },
  {
    id: 2,
    date: "17 Nov",
    name: "Filtir",
    rating: 3,
    featured: true,
    tags: ["Education"],
    image: "/filtir.png",

    description:
      "Filtir is an AI tool that offers a fact-checking chat plugin for content authors. The tool assesses written body text to determine whether there is public and auditable evidence to support the claims made. If a claim lac.",
  },
  {
    id: 3,
    date: "17 Nov",
    name: "Illuminarty",
    rating: 2.1,
    featured: false,
    tags: ["AI Detection", "Students"],
    image: "/illuminarty.png",

    description:
      "Illuminarty is an AI tool that focuses on content detection, specifically detecting AI-generated images and texts.It offers various functionalities to help users understand whether an image or text has been generated by ",
  },
];
